apiVersion: apps/v1
kind: Deployment
metadata:
  name: magda-llm-api-fastchat-api-server
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: magda-llm-api-fastchat-api-server
  template:
    metadata:
      labels:
        service: magda-llm-api-fastchat-api-server
    spec:
      {{- $imageEnv := omit . "Values" }}
      {{- $_ := set $imageEnv "Values" (omit .Values "image") }}
      {{- $_ := set $imageEnv.Values "image" .Values.fastChatImage }}
      {{- include "magda.imagePullSecrets" $imageEnv | indent 6 }}
      containers:
      - name: magda-llm-api
        image: {{ include "magda.image" $imageEnv | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" $imageEnv | quote }}
        ports:
        - containerPort: {{ .Values.fastChatApiServer.port }}
        command:
          - python3.9
          - -m
          - fastchat.serve.openai_api_server
          - --host
          - "0.0.0.0"
          - --port
          - {{ .Values.fastChatApiServer.port | quote }}
          - --controller-address
          - "http://magda-llm-api-fastchat-controller:{{ .Values.fastChatController.port }}"
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ps -ef | grep fastchat.serve.openai_api_server | grep -v grep
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ps -ef | grep fastchat.serve.openai_api_server | grep -v grep
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 30
{{- end }}
        resources:
{{ toYaml .Values.fastChatApiServer.resources | indent 10 }}
      #   volumeMounts:
      #   - name: app-config-volume
      #     mountPath: /etc/config
      # volumes:
      # - name: app-config-volume
      #   configMap:
      #     name: search-api-app-conf
