apiVersion: v1
kind: Service
metadata:
  name: magda-llm-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.fastChatApiServer.port }}
      targetPort: {{ .Values.fastChatApiServer.targetPort }}
  selector:
    service: magda-llm-api-fastchat-api-server
