apiVersion: v1
kind: Service
metadata:
  name: magda-llm-api-fastchat-controller
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.fastChatController.port }} 
  selector:
    service: magda-llm-api-fastchat-controller
