apiVersion: v1
kind: Service
metadata:
  name: magda-llm-api-proxy-server
spec:
  type: ClusterIP
  ports:
    - name: controller-server
      port: {{ .Values.proxyServer.controllerServerPort }}
    - name: service-server
      port: {{ .Values.proxyServer.serviceServerPort }}
  selector:
    service: magda-llm-api-proxy-server
