apiVersion: apps/v1
kind: Deployment
metadata:
  name: magda-llm-api-proxy-server
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: magda-llm-api-proxy-server
  template:
    metadata:
      labels:
        service: magda-llm-api-proxy-server
    spec:
      {{- $imageEnv := omit . "Values" }}
      {{- $_ := set $imageEnv "Values" (omit .Values "image") }}
      {{- $_ := set $imageEnv.Values "image" .Values.httpServiceAgentImage }}
      {{- include "magda.imagePullSecrets" $imageEnv | indent 6 }}
      containers:
      - name: magda-llm-proxy-server
        image: {{ include "magda.image" $imageEnv | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" $imageEnv | quote }}
        ports:
        - containerPort: {{ .Values.proxyServer.controllerServerPort }}
        {{- if ne .Values.proxyServer.serviceServerPort .Values.proxyServer.controllerServerPort }}
        - containerPort: {{ .Values.proxyServer.serviceServerPort }}
        {{- end }}
        command:
          - node
          - /usr/src/app/component/dist/startServer.js
          - --config
          - /etc/appConfig/config.json
          - --accessKeysFile
          - /etc/appKeys/access-keys.json
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: /__status/liveness
            port: {{ .Values.proxyServer.serviceServerPort }}
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /__status/readiness
            port: {{ .Values.proxyServer.serviceServerPort }}
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 30
{{- end }}
        resources:
{{ toYaml .Values.proxyServer.resources | indent 10 }}
        volumeMounts:
        - name: app-config-volume
          mountPath: /etc/appConfig
        - name: api-keys-volume
          mountPath: /etc/appKeys
      volumes:
      - name: app-config-volume
        configMap:
          name: magda-llm-proxy-server-config
      - name: api-keys-volume
        secret:
          secretName: {{ .Values.proxyServer.accessKeySecretName | quote }}
